@file:Suppress("ktlint:standard:no-wildcard-imports")

package com.dessalines.thumbkey.keyboards

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import com.dessalines.thumbkey.utils.*
import com.dessalines.thumbkey.utils.ColorVariant.*
import com.dessalines.thumbkey.utils.FontSizeVariant.*
import com.dessalines.thumbkey.utils.KeyAction.*
import com.dessalines.thumbkey.utils.SwipeNWay.*

val KB_EN_FR_TWO_THUMB_MAIN =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("p", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("q"),
                    // left = KeyC(" "),
                    bottom = KeyC("æ"),
                    //top = KeyC("æ"),
                ),
                KeyItemC(
                    center = KeyC("i", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("ì"),
                    left = KeyC("í"),
                    bottom = KeyC("î"),
                    top = KeyC("ï"),
                ),
                KeyItemC(
                    center = KeyC("h", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("#"),
                    bottom = KeyC("œ"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("n", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("ñ"),
                    left = KeyC("~"),
                    bottom = KeyC("!"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("r", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("z"),
                    left = KeyC("k"),
                    bottom = KeyC("_"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("l", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("\\"),
                    left = KeyC("/"),
                    bottom = KeyC("|"),
                    top = KeyC("&"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("a", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("à"),
                    left = KeyC("á"),
                    bottom = KeyC("â"),
                    top = KeyC("ä"),
                ),
                KeyItemC(
                    center = KeyC("e", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("è"),
                    left = KeyC("é"),
                    bottom = KeyC("ê"),
                    top = KeyC("ë"),
                ),
                KeyItemC(
                    center = KeyC("o", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("ò"),
                    left = KeyC("ó"),
                    bottom = KeyC("ô"),
                    top = KeyC("ö"),
                ),
                KeyItemC(
                    center = KeyC("s", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("\""),
                    left = KeyC("'"),
                    bottom = KeyC("`"),
                    top = KeyC("w"),
                ),
                KeyItemC(
                    center = KeyC("t", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("y"),
                    // bottom = KeyC(" "),
                    top = KeyC("ÿ"),
                ),
                KeyItemC(
                    center = KeyC("m", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("g"),
                    // bottom = KeyC(" "),
                    top = KeyC("µ"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("b", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("("),
                    // left = KeyC(" "),
                    // bottom = KeyC(";"),
                    top = KeyC("@"),
                ),
                KeyItemC(
                    center = KeyC("v", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC(";"),
                    left = KeyC(")"),
                    bottom = KeyC(","),
                    top = KeyC("-"),
                ),
                KeyItemC(
                    center = KeyC("f", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC(":"),
                    left = KeyC("…"),
                    bottom = KeyC("."),
                    top = KeyC("·"),
                ),
                KeyItemC(
                    center = KeyC("c", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("ç"),
                    left = KeyC("x"),
                    bottom = KeyC("?"),
                    top = KeyC("v"),
                ),
                KeyItemC(
                    center = KeyC("u", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("ù"),
                    left = KeyC("ú"),
                    bottom = KeyC("û"),
                    top = KeyC("ü"),
                ),
                KeyItemC(
                    center = KeyC("d", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("j"),
                    // bottom = KeyC(" "),
                    // top = KeyC(" "),
                ),
            ),
            listOf(
                NUMERIC_KEY_ITEM,
                EMOJI_KEY_ITEM,
                SPACEBAR_FRENCH_KEY_ITEM.copy(
                    widthMultiplier = 2,
                    top =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropUp),
                            action = ToggleShiftMode(true),
                            swipeReturnAction = ToggleCurrentWordCapitalization(true),
                            color = MUTED,
                        ),
                    bottom =
                        KeyC(
                            ToggleShiftMode(false),
                            swipeReturnAction = ToggleCurrentWordCapitalization(false),
                        ),
                ),
                BACKSPACE_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_EN_FR_TWO_THUMB_SHIFTED =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("P", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Q"),
                    // left = KeyC(" "),
                    bottom = KeyC("Æ"),
                    //top = KeyC("æ"),
                ),
                KeyItemC(
                    center = KeyC("I", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Ì"),
                    left = KeyC("Í"),
                    bottom = KeyC("Î"),
                    top = KeyC("Ï"),
                ),
                KeyItemC(
                    center = KeyC("H", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("#"),
                    bottom = KeyC("Œ"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("N", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Ñ"),
                    left = KeyC("~"),
                    bottom = KeyC("!"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("R", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Z"),
                    left = KeyC("K"),
                    bottom = KeyC("_"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("L", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("\\"),
                    left = KeyC("/"),
                    bottom = KeyC("|"),
                    top = KeyC("&"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("A", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("À"),
                    left = KeyC("Á"),
                    bottom = KeyC("Â"),
                    top = KeyC("Ä"),
                ),
                KeyItemC(
                    center = KeyC("E", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("È"),
                    left = KeyC("É"),
                    bottom = KeyC("Ê"),
                    top = KeyC("Ë"),
                ),
                KeyItemC(
                    center = KeyC("O", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Ò"),
                    left = KeyC("Ó"),
                    bottom = KeyC("Ô"),
                    top = KeyC("Ö"),
                ),
                KeyItemC(
                    center = KeyC("S", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("\""),
                    left = KeyC("'"),
                    bottom = KeyC("`"),
                    top = KeyC("W"),
                ),
                KeyItemC(
                    center = KeyC("T", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("Y"),
                    // bottom = KeyC(" "),
                    top = KeyC("Ÿ"),
                ),
                KeyItemC(
                    center = KeyC("M", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("G"),
                    // bottom = KeyC(" "),
                    top = KeyC("µ"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("B", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("("),
                    // left = KeyC(" "),
                    // bottom = KeyC(";"),
                    top = KeyC("@"),
                ),
                KeyItemC(
                    center = KeyC("V", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC(";"),
                    left = KeyC(")"),
                    bottom = KeyC(","),
                    top = KeyC("-"),
                ),
                KeyItemC(
                    center = KeyC("F", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC(":"),
                    left = KeyC("…"),
                    bottom = KeyC("."),
                    top = KeyC("·"),
                ),
                KeyItemC(
                    center = KeyC("C", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Ç"),
                    left = KeyC("X"),
                    bottom = KeyC("?"),
                    top = KeyC("V"),
                ),
                KeyItemC(
                    center = KeyC("U", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("Ù"),
                    left = KeyC("Ú"),
                    bottom = KeyC("Û"),
                    top = KeyC("Ü"),
                ),
                KeyItemC(
                    center = KeyC("D", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    left = KeyC("J"),
                    // bottom = KeyC(" "),
                    // top = KeyC(" "),
                ),
            ),
            listOf(
                NUMERIC_KEY_ITEM,
                EMOJI_KEY_ITEM,
                SPACEBAR_FRENCH_KEY_ITEM.copy(
                    widthMultiplier = 2,
                    bottom =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropDown),
                            action = ToggleShiftMode(false),
                            swipeReturnAction = ToggleCurrentWordCapitalization(false),
                            color = MUTED,
                        ),
                    top =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.KeyboardCapslock),
                            capsModeDisplay = KeyDisplay.IconDisplay(Icons.Outlined.Copyright),
                            action = ToggleCapsLock,
                            swipeReturnAction = ToggleCurrentWordCapitalization(true),
                            color = MUTED,
                        ),
                ),
                BACKSPACE_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_EN_FR_TWO_THUMB_NUMERIC =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("%", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("À"),
                    // left = KeyC("Á"),
                    // bottom = KeyC("Â"),
                    // top = KeyC("Ä"),
                ),
                KeyItemC(
                    center = KeyC("/", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("Ì"),
                    // left = KeyC("Í"),
                    bottom = KeyC("="),
                    // top = KeyC("Ï"),
                ),
                KeyItemC(
                    center = KeyC("7", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("#"),
                    // bottom = KeyC("Œ"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("8", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("Ñ"),
                    // left = KeyC("~"),
                    // bottom = KeyC("!"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("0", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("Z"),
                    // left = KeyC("K"),
                    // bottom = KeyC("_"),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("*", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("\\"),
                    // left = KeyC("/"),
                    // bottom = KeyC("|"),
                    // top = KeyC("&"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("<", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("{"),
                    // left = KeyC(" "),
                    bottom = KeyC("["),
                    // top = KeyC("Æ"),
                ),
                KeyItemC(
                    center = KeyC(">", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("È"),
                    left = KeyC("}"),
                    bottom = KeyC("]"),
                    // top = KeyC("Ë"),
                ),
                KeyItemC(
                    center = KeyC("4", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("Ò"),
                    // left = KeyC("Ó"),
                    // bottom = KeyC("Ô"),
                    // top = KeyC("Ö"),
                ),
                KeyItemC(
                    center = KeyC("5", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("\""),
                    // left = KeyC("'"),
                    // bottom = KeyC("`"),
                    // top = KeyC("W"),
                ),
                KeyItemC(
                    center = KeyC("6", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("Y"),
                    // bottom = KeyC(" "),
                    // top = KeyC(" "),
                ),
                KeyItemC(
                    center = KeyC("-", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("G"),
                    // bottom = KeyC(" "),
                    // top = KeyC("Ÿ"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("(", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("("),
                    // left = KeyC(" "),
                    // bottom = KeyC(";"),
                    top = KeyC("^"),
                ),
                KeyItemC(
                    center = KeyC(")", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("€"),
                    left = KeyC("£"),
                    // bottom = KeyC(","),
                    top = KeyC("$"),
                ),
                KeyItemC(
                    center = KeyC("1", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(":"),
                    // left = KeyC("…"),
                    // bottom = KeyC("."),
                    // top = KeyC("·"),
                ),
                KeyItemC(
                    center = KeyC("2", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("X"),
                    // left = KeyC("Ç"),
                    // bottom = KeyC("?"),
                    // top = KeyC("V"),
                ),
                KeyItemC(
                    center = KeyC("3", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC("Ù"),
                    // left = KeyC("Ú"),
                    // bottom = KeyC("Û"),
                    // top = KeyC("Ü"),
                ),
                KeyItemC(
                    center = KeyC("+", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("J"),
                    // bottom = KeyC(" "),
                    // top = KeyC(" "),
                ),
            ),
            listOf(
            ABC_KEY_ITEM,
                KeyItemC(
                    center = KeyC(",", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("J"),
                    // bottom = KeyC(" "),
                    top = KeyC(";"),
                ),
                KeyItemC(
                    center = KeyC("0", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("\""),
                    left = KeyC("°"),
                    // bottom = KeyC(" "),
                    top = KeyC("'"),
                ),
                KeyItemC(
                    center = KeyC(".", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    // right = KeyC(" "),
                    // left = KeyC("J"),
                    // bottom = KeyC(" "),
                    top = KeyC(":"),
                ),
                BACKSPACE_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_EN_FR_TWO_THUMB: KeyboardDefinition =
    KeyboardDefinition(
        title = "english français two thumb",
        modes =
            KeyboardDefinitionModes(
                main = KB_EN_FR_TWO_THUMB_MAIN,
                shifted = KB_EN_FR_TWO_THUMB_SHIFTED,
                numeric = KB_EN_FR_TWO_THUMB_NUMERIC,
            ),
    )
