@file:Suppress("ktlint:standard:no-wildcard-imports")

package com.dessalines.thumbkey.keyboards

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import com.dessalines.thumbkey.utils.*
import com.dessalines.thumbkey.utils.ColorVariant.*
import com.dessalines.thumbkey.utils.FontSizeVariant.*
import com.dessalines.thumbkey.utils.KeyAction.*
import com.dessalines.thumbkey.utils.SwipeNWay.*

val KB_EN_FR_TWO_THUMB_ROMDUD_MAIN =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("p", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("q"),
                    bottom = KeyC("qu"),
                    right = KeyC("pl"),
		    bottomRight = KeyC("po"),
                ),
                KeyItemC(
                    center = KeyC("l", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("la"),
                    bottom = KeyC("lo"),
		    left = KeyC("lp"),
		    top = KeyC("ll"),
                ),
                KeyItemC(
                    center = KeyC("a", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("al"),
                    bottom = KeyC("an"),
                    bottomLeft = KeyC("à"),
		    topLeft = KeyC("â"),
                    bottomRight = KeyC("at"),
                    right = KeyC("ai"),
                ),
                KeyItemC(
                    center = KeyC("i", size = LARGE),
                    swipeType = EIGHT_WAY,
                    right = KeyC("is"),
                    bottom = KeyC("it"),
                    topLeft = KeyC("î"),
                    topRight = KeyC("ï"),
                    bottomLeft = KeyC("in"),
		    bottomRight = KeyC("ie"),
                    left = KeyC("ia"),
                ),
                KeyItemC(
                    center = KeyC("s", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("si"),
                    right = KeyC("sc"),
		    top = KeyC("ss"),
                    bottom = KeyC("se"),
		    bottomLeft = KeyC("st"),
		    bottomRight = KeyC("sm"),
                ),
                KeyItemC(
                    center = KeyC("c", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("k"),
                    right = KeyC("ç"),
                    bottom = KeyC("ch"),
                    bottomLeft = KeyC("ce"),
                    bottomRight = KeyC("ée"),
                    left = KeyC("cs"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("f", size = LARGE),
                    swipeType = EIGHT_WAY,
                    right = KeyC("fo"),
                    top = KeyC("y"),
		    bottom = KeyC("x"),
                    topRight = KeyC("fl"),
                    bottomRight = KeyC("fu"),
                ),
                KeyItemC(
                    center = KeyC("o", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("ol"),
                    left = KeyC("of"),
                    bottom = KeyC("ou"),
                    right = KeyC("on"),
                    topLeft = KeyC("op"),
                    topRight = KeyC("ô"),
                    bottomLeft = KeyC("ov"),
                    bottomRight = KeyC("œ"),
                ),
                KeyItemC(
                    center = KeyC("n", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("na"),
                    left = KeyC("no"),
                    right = KeyC("nt"),
                    bottom = KeyC("…"),
                    bottomLeft = KeyC("nu"),
                    bottomRight = KeyC("nd"),
		    topRight = KeyC("ni"),
                ),
                KeyItemC(
                    center = KeyC("t", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("ti"),
                    bottom = KeyC("z"),
                    right = KeyC("te"),
                    left = KeyC("tn"),
		    topLeft = KeyC("ta"),
		    bottomRight = KeyC("tr"),
		    bottomLeft = KeyC("th"),
                ),
                KeyItemC(
                    center = KeyC("e", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("es"),
                    left = KeyC("et"),
                    bottom = KeyC("er"),
                    right = KeyC("em"),
                    topLeft = KeyC("ê"),
                    topRight = KeyC("ë"),
                    bottomLeft = KeyC("é"),
                    bottomRight = KeyC("è"),
                ),
                KeyItemC(
                    center = KeyC("m", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    left = KeyC("me"),
                    bottom = KeyC("w"),
		    right = KeyC("-"),
		    top = KeyC("mm"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("v", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("j"),
                    right = KeyC("vu"),
                    bottom = KeyC("’"),
		    topRight = KeyC("vo"),
                ),
                KeyItemC(
                    center = KeyC("u", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("uo"),
                    left = KeyC("uv"),
                    topLeft = KeyC("û"),
                    topRight = KeyC("un"),
                    bottomRight = KeyC("ù"),
                    bottom = KeyC("!"),
                ),
                KeyItemC(
                    center = KeyC("h", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("hu"),
                    bottom = KeyC("."),
                    right = KeyC(":"),
		    topLeft = KeyC("ho"),
                ),
                KeyItemC(
                    center = KeyC("d", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("b"),
                    right = KeyC("dr"),
                    bottom = KeyC(","),
                    left = KeyC(";"),
		    topRight = KeyC("de"),
                ),
                KeyItemC(
                    center = KeyC("r", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("re"),
                    left = KeyC("rd"),
                    right = KeyC("rg"),
                    bottom = KeyC("?"),
		    topLeft = KeyC("rt"),
		    topRight = KeyC("rm"),
                ),
                KeyItemC(
                    center = KeyC("g", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("gr"),
                    bottom = KeyC("’"),
                    top = KeyC("@"),
		    topLeft = KeyC("ge"),
                ),
            ),
            listOf(
                NUMERIC_KEY_ITEM,
                EMOJI_KEY_ITEM,
                SPACEBAR_FRENCH_KEY_ITEM.copy(
                    widthMultiplier = 2,
                    top =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropUp),
                            action = ToggleShiftMode(true),
                            swipeReturnAction = ToggleCurrentWordCapitalization(true),
                            color = MUTED,
                        ),
                    bottom =
                        KeyC(
                            ToggleShiftMode(false),
                            swipeReturnAction = ToggleCurrentWordCapitalization(false),
                        ),
                ),
                BACKSPACE_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_EN_FR_TWO_THUMB_ROMDUD_SHIFTED =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("P", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("Q"),
		    bottomRight = KeyC("Po"),
                    bottom = KeyC("Qu"),
                    right = KeyC("Pl"),
                ),
                KeyItemC(
                    center = KeyC("L", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    right = KeyC("La"),
                    bottom = KeyC("Lo"),
                ),
                KeyItemC(
                    center = KeyC("A", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("Al"),
                    bottom = KeyC("An"),
                    bottomLeft = KeyC("À"),
		    topLeft = KeyC("Â"),
                    bottomRight = KeyC("At"),
                    right = KeyC("Ai"),
                ),
                KeyItemC(
                    center = KeyC("I", size = LARGE),
                    swipeType = EIGHT_WAY,
                    right = KeyC("Is"),
                    bottom = KeyC("It"),
                    topLeft = KeyC("Î"),
                    topRight = KeyC("Ï"),
                ),
                KeyItemC(
                    center = KeyC("S", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("Si"),
                    right = KeyC("Sc"),
                    bottom = KeyC("Se"),
		    bottomLeft = KeyC("St"),
		    bottomRight = KeyC("Sm"),
                ),
                KeyItemC(
                    center = KeyC("C", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("K"),
                    right = KeyC("Ç"),
                    bottom = KeyC("Ch"),
                    bottomLeft = KeyC("Ce"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("F", size = LARGE),
                    swipeType = EIGHT_WAY,
                    right = KeyC("Fo"),
                    top = KeyC("Y"),
		    bottom = KeyC("X"),
                    topRight = KeyC("Fl"),
                    bottomRight = KeyC("Fu"),
                ),
                KeyItemC(
                    center = KeyC("O", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("Ol"),
                    left = KeyC("Of"),
                    bottom = KeyC("Ou"),
                    right = KeyC("On"),
                    topLeft = KeyC("Op"),
                    topRight = KeyC("Ô"),
                    bottomLeft = KeyC("Ov"),
                    bottomRight = KeyC("Œ"),
                ),
                KeyItemC(
                    center = KeyC("N", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("Na"),
                    left = KeyC("No"),
                    bottom = KeyC("…"),
                    bottomLeft = KeyC("Nu"),
		    topRight = KeyC("Ni"),
                ),
                KeyItemC(
                    center = KeyC("T", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("Ti"),
                    bottom = KeyC("Z"),
                    right = KeyC("Te"),
		    topLeft = KeyC("Ta"),
		    bottomRight = KeyC("Tr"),
		    bottomLeft = KeyC("Th"),
                ),
                KeyItemC(
                    center = KeyC("E", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("Es"),
                    left = KeyC("Et"),
                    bottom = KeyC("Er"),
                    right = KeyC("Em"),
                    topLeft = KeyC("Ê"),
                    bottomLeft = KeyC("É"),
                    bottomRight = KeyC("È"),
                ),
                KeyItemC(
                    center = KeyC("M", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    left = KeyC("Me"),
                    bottom = KeyC("W"),
		    right = KeyC("-"),
                ),
            ),
            listOf(
                KeyItemC(
                    center = KeyC("V", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("J"),
                    right = KeyC("Vu"),
                    bottom = KeyC("’"),
		    topRight = KeyC("Vo"),
                ),
                KeyItemC(
                    center = KeyC("U", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("Uv"),
                    topLeft = KeyC("Û"),
                    topRight = KeyC("Un"),
                    bottomRight = KeyC("Ù"),
                    bottom = KeyC("!"),
                ),
                KeyItemC(
                    center = KeyC("H", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("Hu"),
                    bottom = KeyC("."),
                    right = KeyC(":"),
		    topLeft = KeyC("Ho"),
                ),
                KeyItemC(
                    center = KeyC("D", size = LARGE),
                    swipeType = EIGHT_WAY,
                    top = KeyC("B"),
                    right = KeyC("Dr"),
                    bottom = KeyC(","),
                    left = KeyC(";"),
		    topRight = KeyC("De"),
                ),
                KeyItemC(
                    center = KeyC("R", size = LARGE),
                    swipeType = FOUR_WAY_CROSS,
                    top = KeyC("Re"),
                    bottom = KeyC("?"),
                ),
                KeyItemC(
                    center = KeyC("G", size = LARGE),
                    swipeType = EIGHT_WAY,
                    left = KeyC("Gr"),
                    bottom = KeyC("’"),
                    top = KeyC("@"),
		    topLeft = KeyC("Ge"),
                ),
            ),
            listOf(
                NUMERIC_KEY_ITEM,
                EMOJI_KEY_ITEM,
                SPACEBAR_FRENCH_KEY_ITEM.copy(
                    widthMultiplier = 2,
                    bottom =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropDown),
                            action = ToggleShiftMode(false),
                            swipeReturnAction = ToggleCurrentWordCapitalization(false),
                            color = MUTED,
                        ),
                    top =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.KeyboardCapslock),
                            capsModeDisplay = KeyDisplay.IconDisplay(Icons.Outlined.Copyright),
                            action = ToggleCapsLock,
                            swipeReturnAction = ToggleCurrentWordCapitalization(true),
                            color = MUTED,
                        ),
                ),
                BACKSPACE_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_EN_FR_TWO_THUMB_ROMDUD: KeyboardDefinition =
    KeyboardDefinition(
        title = "english français two thumb (Romdud)",
        modes =
            KeyboardDefinitionModes(
                main = KB_EN_FR_TWO_THUMB_ROMDUD_MAIN,
                shifted = KB_EN_FR_TWO_THUMB_ROMDUD_SHIFTED,
                numeric = KB_EN_FR_TWO_THUMB_NUMERIC,
            ),
    )
